### ISSUE TITLE
IntelliFileSetup.msi: Unknown author

### ISSUE THREAD

**Issue by gmacario** [mihaimoga/IntelliFile#3]
Hello,

I went to https://www.emvs.site/intellifile/
then clicked the "Download" button to download the binary release.

https://www.emvs.site/freeware/IntelliFileSetup.msi

When I try to install the software by clicking on "IntelliFileSetup.msi" I receive the following message

![image](https://github.com/mihaimoga/IntelliFile/assets/75182/fbeee8b0-ec6b-43b7-9a22-c12a65fffb03)

If I click on "Ulteriori informazioni"

![image](https://github.com/mihaimoga/IntelliFile/assets/75182/3cb59a30-cc8a-41f2-b19f-cf198d295a57)

**Comment by mihaimoga** [comment]
I'm sorry, I don't understand italian.
Still, I believe it has to do with the fact that I'm not a known author.
If you click on More, and than Run anyway, it should work.

![CaptureRunAnyway](https://github.com/mihaimoga/IntelliFile/assets/1273027/843a9ecf-7c19-41d9-af07-70f78d59b813)

**Comment by gmacario** [comment]
Understood. I raised the issue since this might frighten potential users of the program.

Anyway, keep up the good work!

**Comment by mihaimoga** [comment]
Thank you!
